const SURF_SPOTS = [
  {
    id: 'scheveningen-nl',
    region: 'eu',
    coastOrientationDeg: 270,
    naam: 'Scheveningen',
    land: 'Nederland',
    latitude: 52.11,
    longitude: 4.26,
    golfHoogteMeter: 1.2,
    golfPeriodeSeconden: 8,
    windSnelheidKnopen: 14,
    windRichting: 'NO',
    watertemperatuurC: 17
  },
  {
    id: 'hossegor-fr',
    region: 'eu',
    coastOrientationDeg: 270,
    naam: 'Hossegor',
    land: 'Frankrijk',
    latitude: 43.665,
    longitude: -1.443,
    golfHoogteMeter: 1.9,
    golfPeriodeSeconden: 11,
    windSnelheidKnopen: 12,
    windRichting: 'W',
    watertemperatuurC: 19
  },
  {
    id: 'jeffreys-bay-za',
    region: 'af',
    coastOrientationDeg: 140,
    naam: 'Jeffreys Bay',
    land: 'Zuid-Afrika',
    latitude: -34.05,
    longitude: 24.93,
    golfHoogteMeter: 2.4,
    golfPeriodeSeconden: 13,
    windSnelheidKnopen: 10,
    windRichting: 'ZW',
    watertemperatuurC: 21
  },
  {
    id: 'pipeline-us-hi',
    region: 'am',
    coastOrientationDeg: 10,
    naam: 'Pipeline',
    land: 'Hawaï',
    latitude: 21.665,
    longitude: -158.051,
    golfHoogteMeter: 2.8,
    golfPeriodeSeconden: 14,
    windSnelheidKnopen: 16,
    windRichting: 'NO',
    watertemperatuurC: 25
  },
  {
    id: 'ericeira-pt',
    region: 'eu',
    coastOrientationDeg: 270,
    naam: 'Ericeira',
    land: 'Portugal',
    latitude: 38.963,
    longitude: -9.417,
    golfHoogteMeter: 1.7,
    golfPeriodeSeconden: 10,
    windSnelheidKnopen: 11,
    windRichting: 'NW',
    watertemperatuurC: 18
  },
  {
    id: 'peniche-pt',
    region: 'eu',
    coastOrientationDeg: 260,
    naam: 'Peniche',
    land: 'Portugal',
    latitude: 39.355,
    longitude: -9.381,
    golfHoogteMeter: 1.8,
    golfPeriodeSeconden: 11,
    windSnelheidKnopen: 13,
    windRichting: 'NW',
    watertemperatuurC: 18
  },
  {
    id: 'nazare-pt',
    region: 'eu',
    coastOrientationDeg: 270,
    naam: 'Nazaré',
    land: 'Portugal',
    latitude: 39.602,
    longitude: -9.07,
    golfHoogteMeter: 2.6,
    golfPeriodeSeconden: 13,
    windSnelheidKnopen: 15,
    windRichting: 'W',
    watertemperatuurC: 17
  },
  {
    id: 'carcavelos-pt',
    region: 'eu',
    coastOrientationDeg: 240,
    naam: 'Carcavelos',
    land: 'Portugal',
    latitude: 38.676,
    longitude: -9.337,
    golfHoogteMeter: 1.4,
    golfPeriodeSeconden: 9,
    windSnelheidKnopen: 12,
    windRichting: 'NW',
    watertemperatuurC: 18
  },
  {
    id: 'mundaka-es',
    region: 'eu',
    coastOrientationDeg: 350,
    naam: 'Mundaka',
    land: 'Spanje',
    latitude: 43.408,
    longitude: -2.697,
    golfHoogteMeter: 1.6,
    golfPeriodeSeconden: 10,
    windSnelheidKnopen: 11,
    windRichting: 'W',
    watertemperatuurC: 17
  },
  {
    id: 'zarautz-es',
    region: 'eu',
    coastOrientationDeg: 355,
    naam: 'Zarautz',
    land: 'Spanje',
    latitude: 43.287,
    longitude: -2.173,
    golfHoogteMeter: 1.5,
    golfPeriodeSeconden: 9,
    windSnelheidKnopen: 14,
    windRichting: 'NW',
    watertemperatuurC: 18
  },
  {
    id: 'sopelana-es',
    region: 'eu',
    coastOrientationDeg: 350,
    naam: 'Sopelana',
    land: 'Spanje',
    latitude: 43.379,
    longitude: -2.997,
    golfHoogteMeter: 1.7,
    golfPeriodeSeconden: 10,
    windSnelheidKnopen: 13,
    windRichting: 'W',
    watertemperatuurC: 17
  },
  {
    id: 'biarritz-fr',
    region: 'eu',
    coastOrientationDeg: 300,
    naam: 'Biarritz',
    land: 'Frankrijk',
    latitude: 43.483,
    longitude: -1.558,
    golfHoogteMeter: 1.8,
    golfPeriodeSeconden: 11,
    windSnelheidKnopen: 12,
    windRichting: 'W',
    watertemperatuurC: 19
  },
  {
    id: 'lacanau-fr',
    region: 'eu',
    coastOrientationDeg: 270,
    naam: 'Lacanau',
    land: 'Frankrijk',
    latitude: 45.0,
    longitude: -1.202,
    golfHoogteMeter: 1.7,
    golfPeriodeSeconden: 10,
    windSnelheidKnopen: 13,
    windRichting: 'NW',
    watertemperatuurC: 18
  },
  {
    id: 'la-torche-fr',
    region: 'eu',
    coastOrientationDeg: 260,
    naam: 'La Torche',
    land: 'Frankrijk',
    latitude: 47.84,
    longitude: -4.368,
    golfHoogteMeter: 1.9,
    golfPeriodeSeconden: 11,
    windSnelheidKnopen: 14,
    windRichting: 'W',
    watertemperatuurC: 16
  },
  {
    id: 'newquay-uk',
    region: 'eu',
    coastOrientationDeg: 300,
    naam: 'Newquay',
    land: 'Verenigd Koninkrijk',
    latitude: 50.416,
    longitude: -5.073,
    golfHoogteMeter: 1.6,
    golfPeriodeSeconden: 9,
    windSnelheidKnopen: 15,
    windRichting: 'ZW',
    watertemperatuurC: 15
  },
  {
    id: 'thurso-east-uk',
    region: 'eu',
    coastOrientationDeg: 60,
    naam: 'Thurso East',
    land: 'Verenigd Koninkrijk',
    latitude: 58.595,
    longitude: -3.522,
    golfHoogteMeter: 2.0,
    golfPeriodeSeconden: 12,
    windSnelheidKnopen: 16,
    windRichting: 'W',
    watertemperatuurC: 12
  },
  {
    id: 'uluwatu-id',
    region: 'ap',
    coastOrientationDeg: 200,
    naam: 'Uluwatu',
    land: 'Indonesië',
    latitude: -8.829,
    longitude: 115.084,
    golfHoogteMeter: 2.1,
    golfPeriodeSeconden: 12,
    windSnelheidKnopen: 9,
    windRichting: 'ZO',
    watertemperatuurC: 27
  },
  {
    id: 'anchor-point-ma',
    region: 'af',
    coastOrientationDeg: 320,
    naam: 'Anchor Point',
    land: 'Marokko',
    latitude: 30.544,
    longitude: -9.709,
    golfHoogteMeter: 1.9,
    golfPeriodeSeconden: 11,
    windSnelheidKnopen: 12,
    windRichting: 'NO',
    watertemperatuurC: 19
  },
  {
    id: 'taghazout-ma',
    region: 'af',
    coastOrientationDeg: 320,
    naam: 'Taghazout',
    land: 'Marokko',
    latitude: 30.545,
    longitude: -9.711,
    golfHoogteMeter: 1.8,
    golfPeriodeSeconden: 10,
    windSnelheidKnopen: 11,
    windRichting: 'NO',
    watertemperatuurC: 19
  },
  {
    id: 'fuerteventura-es',
    region: 'af',
    coastOrientationDeg: 0,
    naam: 'Fuerteventura',
    land: 'Canarische Eilanden',
    latitude: 28.357,
    longitude: -14.053,
    golfHoogteMeter: 1.7,
    golfPeriodeSeconden: 10,
    windSnelheidKnopen: 15,
    windRichting: 'N',
    watertemperatuurC: 22
  },
  {
    id: 'lanzarote-es',
    region: 'af',
    coastOrientationDeg: 330,
    naam: 'Lanzarote',
    land: 'Canarische Eilanden',
    latitude: 29.047,
    longitude: -13.589,
    golfHoogteMeter: 1.9,
    golfPeriodeSeconden: 11,
    windSnelheidKnopen: 14,
    windRichting: 'N',
    watertemperatuurC: 22
  },
  {
    id: 'santa-cruz-us',
    region: 'am',
    coastOrientationDeg: 240,
    naam: 'Santa Cruz',
    land: 'Verenigde Staten',
    latitude: 36.951,
    longitude: -122.026,
    golfHoogteMeter: 1.8,
    golfPeriodeSeconden: 11,
    windSnelheidKnopen: 10,
    windRichting: 'NW',
    watertemperatuurC: 15
  },
  {
    id: 'huntington-beach-us',
    region: 'am',
    coastOrientationDeg: 220,
    naam: 'Huntington Beach',
    land: 'Verenigde Staten',
    latitude: 33.659,
    longitude: -117.998,
    golfHoogteMeter: 1.4,
    golfPeriodeSeconden: 9,
    windSnelheidKnopen: 9,
    windRichting: 'W',
    watertemperatuurC: 18
  },
  {
    id: 'la-jolla-us',
    region: 'am',
    coastOrientationDeg: 250,
    naam: 'La Jolla',
    land: 'Verenigde Staten',
    latitude: 32.832,
    longitude: -117.271,
    golfHoogteMeter: 1.3,
    golfPeriodeSeconden: 9,
    windSnelheidKnopen: 8,
    windRichting: 'W',
    watertemperatuurC: 19
  },
  {
    id: 'outer-banks-us',
    region: 'am',
    coastOrientationDeg: 95,
    naam: 'Outer Banks',
    land: 'Verenigde Staten',
    latitude: 35.558,
    longitude: -75.466,
    golfHoogteMeter: 1.9,
    golfPeriodeSeconden: 10,
    windSnelheidKnopen: 14,
    windRichting: 'ZW',
    watertemperatuurC: 20
  },
  {
    id: 'arpoador-br',
    region: 'am',
    coastOrientationDeg: 160,
    naam: 'Arpoador',
    land: 'Brazilië',
    latitude: -22.987,
    longitude: -43.191,
    golfHoogteMeter: 1.5,
    golfPeriodeSeconden: 9,
    windSnelheidKnopen: 12,
    windRichting: 'ZO',
    watertemperatuurC: 24
  },
  {
    id: 'punta-de-lobos-cl',
    region: 'am',
    coastOrientationDeg: 250,
    naam: 'Punta de Lobos',
    land: 'Chili',
    latitude: -34.416,
    longitude: -72.034,
    golfHoogteMeter: 2.2,
    golfPeriodeSeconden: 12,
    windSnelheidKnopen: 13,
    windRichting: 'Z',
    watertemperatuurC: 15
  },
  {
    id: 'canggu-id',
    region: 'ap',
    coastOrientationDeg: 220,
    naam: 'Canggu',
    land: 'Indonesië',
    latitude: -8.648,
    longitude: 115.136,
    golfHoogteMeter: 1.8,
    golfPeriodeSeconden: 10,
    windSnelheidKnopen: 10,
    windRichting: 'ZO',
    watertemperatuurC: 28
  },
  {
    id: 'gold-coast-au',
    region: 'ap',
    coastOrientationDeg: 110,
    naam: 'Gold Coast',
    land: 'Australië',
    latitude: -28.016,
    longitude: 153.43,
    golfHoogteMeter: 1.6,
    golfPeriodeSeconden: 10,
    windSnelheidKnopen: 12,
    windRichting: 'O',
    watertemperatuurC: 24
  },
  {
    id: 'manly-au',
    region: 'ap',
    coastOrientationDeg: 100,
    naam: 'Manly',
    land: 'Australië',
    latitude: -33.797,
    longitude: 151.288,
    golfHoogteMeter: 1.5,
    golfPeriodeSeconden: 9,
    windSnelheidKnopen: 13,
    windRichting: 'ZO',
    watertemperatuurC: 22
  },
  {
    id: 'raglan-nz',
    region: 'ap',
    coastOrientationDeg: 270,
    naam: 'Raglan',
    land: 'Nieuw-Zeeland',
    latitude: -37.808,
    longitude: 174.816,
    golfHoogteMeter: 1.9,
    golfPeriodeSeconden: 11,
    windSnelheidKnopen: 11,
    windRichting: 'ZW',
    watertemperatuurC: 18
  }
];
