const SURF_SPOTS = [
  {
    id: 'scheveningen-nl',
    naam: 'Scheveningen',
    land: 'Nederland',
    latitude: 52.11,
    longitude: 4.26,
    golfHoogteMeter: 1.2,
    golfPeriodeSeconden: 8,
    windSnelheidKnopen: 14,
    windRichting: 'NO',
    watertemperatuurC: 17
  },
  {
    id: 'hossegor-fr',
    naam: 'Hossegor',
    land: 'Frankrijk',
    latitude: 43.665,
    longitude: -1.443,
    golfHoogteMeter: 1.9,
    golfPeriodeSeconden: 11,
    windSnelheidKnopen: 12,
    windRichting: 'W',
    watertemperatuurC: 19
  },
  {
    id: 'jeffreys-bay-za',
    naam: 'Jeffreys Bay',
    land: 'Zuid-Afrika',
    latitude: -34.05,
    longitude: 24.93,
    golfHoogteMeter: 2.4,
    golfPeriodeSeconden: 13,
    windSnelheidKnopen: 10,
    windRichting: 'ZW',
    watertemperatuurC: 21
  },
  {
    id: 'pipeline-us-hi',
    naam: 'Pipeline',
    land: 'Hawaï',
    latitude: 21.665,
    longitude: -158.051,
    golfHoogteMeter: 2.8,
    golfPeriodeSeconden: 14,
    windSnelheidKnopen: 16,
    windRichting: 'NO',
    watertemperatuurC: 25
  },
  {
    id: 'ericeira-pt',
    naam: 'Ericeira',
    land: 'Portugal',
    latitude: 38.963,
    longitude: -9.417,
    golfHoogteMeter: 1.7,
    golfPeriodeSeconden: 10,
    windSnelheidKnopen: 11,
    windRichting: 'NW',
    watertemperatuurC: 18
  },
  {
    id: 'peniche-pt',
    naam: 'Peniche',
    land: 'Portugal',
    latitude: 39.355,
    longitude: -9.381,
    golfHoogteMeter: 1.8,
    golfPeriodeSeconden: 11,
    windSnelheidKnopen: 13,
    windRichting: 'NW',
    watertemperatuurC: 18
  },
  {
    id: 'nazare-pt',
    naam: 'Nazaré',
    land: 'Portugal',
    latitude: 39.602,
    longitude: -9.07,
    golfHoogteMeter: 2.6,
    golfPeriodeSeconden: 13,
    windSnelheidKnopen: 15,
    windRichting: 'W',
    watertemperatuurC: 17
  },
  {
    id: 'carcavelos-pt',
    naam: 'Carcavelos',
    land: 'Portugal',
    latitude: 38.676,
    longitude: -9.337,
    golfHoogteMeter: 1.4,
    golfPeriodeSeconden: 9,
    windSnelheidKnopen: 12,
    windRichting: 'NW',
    watertemperatuurC: 18
  },
  {
    id: 'mundaka-es',
    naam: 'Mundaka',
    land: 'Spanje',
    latitude: 43.408,
    longitude: -2.697,
    golfHoogteMeter: 1.6,
    golfPeriodeSeconden: 10,
    windSnelheidKnopen: 11,
    windRichting: 'W',
    watertemperatuurC: 17
  },
  {
    id: 'zarautz-es',
    naam: 'Zarautz',
    land: 'Spanje',
    latitude: 43.287,
    longitude: -2.173,
    golfHoogteMeter: 1.5,
    golfPeriodeSeconden: 9,
    windSnelheidKnopen: 14,
    windRichting: 'NW',
    watertemperatuurC: 18
  },
  {
    id: 'sopelana-es',
    naam: 'Sopelana',
    land: 'Spanje',
    latitude: 43.379,
    longitude: -2.997,
    golfHoogteMeter: 1.7,
    golfPeriodeSeconden: 10,
    windSnelheidKnopen: 13,
    windRichting: 'W',
    watertemperatuurC: 17
  },
  {
    id: 'biarritz-fr',
    naam: 'Biarritz',
    land: 'Frankrijk',
    latitude: 43.483,
    longitude: -1.558,
    golfHoogteMeter: 1.8,
    golfPeriodeSeconden: 11,
    windSnelheidKnopen: 12,
    windRichting: 'W',
    watertemperatuurC: 19
  },
  {
    id: 'lacanau-fr',
    naam: 'Lacanau',
    land: 'Frankrijk',
    latitude: 45.0,
    longitude: -1.202,
    golfHoogteMeter: 1.7,
    golfPeriodeSeconden: 10,
    windSnelheidKnopen: 13,
    windRichting: 'NW',
    watertemperatuurC: 18
  },
  {
    id: 'la-torche-fr',
    naam: 'La Torche',
    land: 'Frankrijk',
    latitude: 47.84,
    longitude: -4.368,
    golfHoogteMeter: 1.9,
    golfPeriodeSeconden: 11,
    windSnelheidKnopen: 14,
    windRichting: 'W',
    watertemperatuurC: 16
  },
  {
    id: 'newquay-uk',
    naam: 'Newquay',
    land: 'Verenigd Koninkrijk',
    latitude: 50.416,
    longitude: -5.073,
    golfHoogteMeter: 1.6,
    golfPeriodeSeconden: 9,
    windSnelheidKnopen: 15,
    windRichting: 'ZW',
    watertemperatuurC: 15
  },
  {
    id: 'thurso-east-uk',
    naam: 'Thurso East',
    land: 'Verenigd Koninkrijk',
    latitude: 58.595,
    longitude: -3.522,
    golfHoogteMeter: 2.0,
    golfPeriodeSeconden: 12,
    windSnelheidKnopen: 16,
    windRichting: 'W',
    watertemperatuurC: 12
  },
  {
    id: 'uluwatu-id',
    naam: 'Uluwatu',
    land: 'Indonesië',
    latitude: -8.829,
    longitude: 115.084,
    golfHoogteMeter: 2.1,
    golfPeriodeSeconden: 12,
    windSnelheidKnopen: 9,
    windRichting: 'ZO',
    watertemperatuurC: 27
  }
];
