name: Feature request
description: Gebruik dit template voor nieuwe features richting v0.2 en verder
title: "Feature: "
labels:
  - feature
body:
  - type: markdown
    attributes:
      value: |
        Gebruik dit issue om een nieuwe feature helder en toetsbaar te beschrijven.

  - type: textarea
    id: samenvatting
    attributes:
      label: Korte samenvatting van de feature
      description: Beschrijf in 1-3 zinnen wat je wilt toevoegen.
      placeholder: Bijvoorbeeld: Voeg een kaartweergave toe waarmee gebruikers spots visueel kunnen selecteren.
    validations:
      required: true

  - type: textarea
    id: probleem_behoefte
    attributes:
      label: Probleem / behoefte van de gebruiker
      description: Welk gebruikersprobleem lost deze feature op?
      placeholder: Bijvoorbeeld: Gebruikers moeten nu handmatig zoeken op naam en missen visuele context van spot-locaties.
    validations:
      required: true

  - type: textarea
    id: voorgestelde_oplossing
    attributes:
      label: Voorgestelde oplossing / UX
      description: Beschrijf de gewenste gebruikersflow en UI-verwachting.
      placeholder: |
        Bijvoorbeeld:
        - Voeg een kaart toe onder de zoekbalk.
        - Klik op marker opent spot-preview.
        - Knop “Bekijk forecast” laadt de bestaande forecastkaart.
    validations:
      required: true

  - type: textarea
    id: technische_schets
    attributes:
      label: Technische schets (optioneel)
      description: Eventuele technische richting, componenten of API-impact.
      placeholder: |
        Bijvoorbeeld:
        - Leaflet integreren voor map rendering.
        - Spots uit spots.js als markers tonen.
        - Geen backend nodig; client-side implementatie.
    validations:
      required: false

  - type: textarea
    id: acceptatiecriteria
    attributes:
      label: Acceptatiecriteria
      description: Beschrijf concrete criteria waaraan de feature moet voldoen.
      placeholder: |
        Bijvoorbeeld:
        - [ ] Gebruiker kan een spot via de kaart selecteren.
        - [ ] Forecast laadt correct na selectie.
        - [ ] Werkt op desktop en mobiel.
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: UX beschreven
          required: false
        - label: Technische impact ingeschat
          required: false
        - label: Eventuele breaking changes beoordeeld
          required: false
        - label: README/changelog bijwerken (indien nodig)
          required: false
